######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 29 19:41:39 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stdafx.h targetver.h
SOURCES += C_Melody.cpp stdafx.cpp
