######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 23 14:23:59 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stdafx.h targetver.h
SOURCES += C_Melody.cpp stdafx.cpp
